namePrefix: dvn-
nameSuffix: -prod
resources:
- backend/deploy.yml
- backend/service.yml
- frontend/deploy.yml
- frontend/service.yml
images:
- name: 917714909985.dkr.ecr.us-east-1.amazonaws.com/workshop/production/backend
  newName: 917714909985.dkr.ecr.us-east-1.amazonaws.com/workshop/production/backend
  newTag: 0fdd59a75d9594afed88e50e351b0072efad27b9
- name: 917714909985.dkr.ecr.us-east-1.amazonaws.com/workshop/production/frontend
  newName: 917714909985.dkr.ecr.us-east-1.amazonaws.com/workshop/production/frontend
  newTag: v3.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
